name: traditional_saju
description: Traditional Saju fortune telling application.
version: 1.0.0+8
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.2.0
  dio: ^5.8.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_sign_in: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  kakao_flutter_sdk: ^1.10.0
  logger: ^2.6.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/oauth_logo/
    - assets/images/item_logo/

  fonts:
    - family: SSRock
      fonts:
        - asset: assets/fonts/SSRockRegular.ttf
    - family: MapoFlowerIsland
      fonts:
        - asset: assets/fonts/MapoFlowerIsland.ttf
    - family: Hakgyoansim
      fonts:
        - asset: assets/fonts/Hakgyoansim.ttf
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-aLt.ttf
          weight: 300
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-bRg.ttf
          weight: 400
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-cBd.ttf
          weight: 700
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-dEb.ttf
          weight: 800
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-eHv.ttf
          weight: 900

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  color_dark: "#555555"
  image_dark: assets/images/splash_dark.png

  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center
